build(deps): bump undici from 5.14.0 to 5.21.0 in /tests/e2e/playwright (#1521)
Bumps [undici](https://github.com/nodejs/undici) from 5.14.0 to 5.21.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/nodejs/undici/releases">undici's releases</a>.</em></p>
<blockquote>
<h2>v5.21.0</h2>
<h2>What's Changed</h2>
<ul>
<li>workflow: add scorecard.yml by <a href="https://github.com/RafaelGSS"><code>@​RafaelGSS</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1942">nodejs/undici#1942</a></li>
<li>ci: timeout CI jobs after 15 minutes by <a href="https://github.com/dominykas"><code>@​dominykas</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1946">nodejs/undici#1946</a></li>
<li>test(wpt): respect variants by <a href="https://github.com/panva"><code>@​panva</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1951">nodejs/undici#1951</a></li>
<li>fix: improve isFormDataLike compat by <a href="https://github.com/ronag"><code>@​ronag</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1953">nodejs/undici#1953</a></li>
<li>fix: flaky fetch tests by <a href="https://github.com/KhafraDev"><code>@​KhafraDev</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1956">nodejs/undici#1956</a></li>
<li>test(wpt): include all testing files by <a href="https://github.com/KhafraDev"><code>@​KhafraDev</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1954">nodejs/undici#1954</a></li>
<li>fix: remove unneeded fetch tests by <a href="https://github.com/KhafraDev"><code>@​KhafraDev</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1960">nodejs/undici#1960</a></li>
<li>fix: use normal timers for delays &lt; 1s by <a href="https://github.com/ronag"><code>@​ronag</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1961">nodejs/undici#1961</a></li>
<li>perf: optimize happy path by <a href="https://github.com/anonrig"><code>@​anonrig</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1955">nodejs/undici#1955</a></li>
<li>fix: 🐛 add URL upstream variations in BalancedPool types by <a href="https://github.com/jimmy-guzman"><code>@​jimmy-guzman</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1966">nodejs/undici#1966</a></li>
<li>test(wpt): handle uncaught exceptions by <a href="https://github.com/KhafraDev"><code>@​KhafraDev</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1965">nodejs/undici#1965</a></li>
<li>Fix failing wpts by <a href="https://github.com/KhafraDev"><code>@​KhafraDev</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1967">nodejs/undici#1967</a></li>
<li>test(wpt): add results to an existing WPT Report by <a href="https://github.com/panva"><code>@​panva</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1944">nodejs/undici#1944</a></li>
<li>fix: strengthen isStream condition checking by <a href="https://github.com/debadree25"><code>@​debadree25</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1969">nodejs/undici#1969</a></li>
<li>fix: implement basic policy container by <a href="https://github.com/KhafraDev"><code>@​KhafraDev</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1970">nodejs/undici#1970</a></li>
<li>TypeScript type fixes, for <a href="https://redirect.github.com/nodejs/undici/issues/1949">#1949</a> by <a href="https://github.com/joshxyzhimself"><code>@​joshxyzhimself</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1968">nodejs/undici#1968</a></li>
<li>websocket: separate connection logic from websocket by <a href="https://github.com/KhafraDev"><code>@​KhafraDev</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1973">nodejs/undici#1973</a></li>
<li>README: h3 not showing ### as a header by <a href="https://github.com/hilleer"><code>@​hilleer</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1975">nodejs/undici#1975</a></li>
<li>wptrunner: expose gc by <a href="https://github.com/KhafraDev"><code>@​KhafraDev</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1974">nodejs/undici#1974</a></li>
<li>perf: cork socket before writing by <a href="https://github.com/ronag"><code>@​ronag</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1982">nodejs/undici#1982</a></li>
<li>fix: fast timers and event loop lag by <a href="https://github.com/ronag"><code>@​ronag</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1977">nodejs/undici#1977</a></li>
<li>fix: correctly calculate resource timing duration by <a href="https://github.com/amilajack"><code>@​amilajack</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1988">nodejs/undici#1988</a></li>
<li>wpt: update tests by <a href="https://github.com/KhafraDev"><code>@​KhafraDev</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1984">nodejs/undici#1984</a></li>
<li>fix: undici stream throwOnError by <a href="https://github.com/dancastillo"><code>@​dancastillo</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1995">nodejs/undici#1995</a></li>
<li>fix: remove unnecessary WeakRef by <a href="https://github.com/ronag"><code>@​ronag</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/2000">nodejs/undici#2000</a></li>
<li>Fix: websocket.d.ts - error TS2304: Cannot find name 'MessagePort' by <a href="https://github.com/ZaBlazzingZephyrus"><code>@​ZaBlazzingZephyrus</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1997">nodejs/undici#1997</a></li>
<li>feat: add abort signal to body.dump() by <a href="https://github.com/debadree25"><code>@​debadree25</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1993">nodejs/undici#1993</a></li>
<li>fix(fetch): third party abortcontrollers throwing errors by <a href="https://github.com/KhafraDev"><code>@​KhafraDev</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/2002">nodejs/undici#2002</a></li>
<li>Improve ProxyAgent example with autentication by <a href="https://github.com/egmen"><code>@​egmen</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/2004">nodejs/undici#2004</a></li>
<li>Add clientFactory option to ProxyAgent by <a href="https://github.com/andrewfecenko"><code>@​andrewfecenko</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/2003">nodejs/undici#2003</a></li>
</ul>
<h2>New Contributors</h2>
<ul>
<li><a href="https://github.com/jimmy-guzman"><code>@​jimmy-guzman</code></a> made their first contribution in <a href="https://redirect.github.com/nodejs/undici/pull/1966">nodejs/undici#1966</a></li>
<li><a href="https://github.com/hilleer"><code>@​hilleer</code></a> made their first contribution in <a href="https://redirect.github.com/nodejs/undici/pull/1975">nodejs/undici#1975</a></li>
<li><a href="https://github.com/amilajack"><code>@​amilajack</code></a> made their first contribution in <a href="https://redirect.github.com/nodejs/undici/pull/1988">nodejs/undici#1988</a></li>
<li><a href="https://github.com/ZaBlazzingZephyrus"><code>@​ZaBlazzingZephyrus</code></a> made their first contribution in <a href="https://redirect.github.com/nodejs/undici/pull/1997">nodejs/undici#1997</a></li>
<li><a href="https://github.com/egmen"><code>@​egmen</code></a> made their first contribution in <a href="https://redirect.github.com/nodejs/undici/pull/2004">nodejs/undici#2004</a></li>
<li><a href="https://github.com/andrewfecenko"><code>@​andrewfecenko</code></a> made their first contribution in <a href="https://redirect.github.com/nodejs/undici/pull/2003">nodejs/undici#2003</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a href="https://github.com/nodejs/undici/compare/v5.20.0...v5.21.0">https://github.com/nodejs/undici/compare/v5.20.0...v5.21.0</a></p>
<h2>v5.20.0</h2>
<h2>What's Changed</h2>
<ul>
<li>perf: improve cookie parsing performance by <a href="https://github.com/KhafraDev"><code>@​KhafraDev</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1931">nodejs/undici#1931</a></li>
<li>fix: disable websocket wpts in ci :( by <a href="https://github.com/KhafraDev"><code>@​KhafraDev</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1932">nodejs/undici#1932</a></li>
<li>fix: Allow “undefined“ as value in headers by <a href="https://github.com/pan93412"><code>@​pan93412</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1929">nodejs/undici#1929</a></li>
<li>feat: Support autoSelectFamily when connecting. by <a href="https://github.com/ShogunPanda"><code>@​ShogunPanda</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1914">nodejs/undici#1914</a></li>
<li>fix: copy cookies when cloning haders by <a href="https://github.com/KhafraDev"><code>@​KhafraDev</code></a> in <a href="https://redirect.github.com/nodejs/undici/pull/1936">nodejs/undici#1936</a></li>
</ul>

</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/nodejs/undici/commit/98b63b25aab030d4aa08be818adebead9ed77788"><code>98b63b2</code></a> Bumped v5.21.0</li>
<li><a href="https://github.com/nodejs/undici/commit/90d45fac4d3a7ff3aa1cca4e8e4309bd7b0244e7"><code>90d45fa</code></a> Add clientFactory option to ProxyAgent (<a href="https://redirect.github.com/nodejs/undici/issues/2003">#2003</a>)</li>
<li><a href="https://github.com/nodejs/undici/commit/1bbcfa22c0b3a53ba74a3fbcc55e76a18f42e81f"><code>1bbcfa2</code></a> Improve ProxyAgent example with autentication (<a href="https://redirect.github.com/nodejs/undici/issues/2004">#2004</a>)</li>
<li><a href="https://github.com/nodejs/undici/commit/06c6488892a4a2210c9646e2aff364f5b6b36b92"><code>06c6488</code></a> fix(fetch): third party abortcontrollers throwing errors (<a href="https://redirect.github.com/nodejs/undici/issues/2002">#2002</a>)</li>
<li><a href="https://github.com/nodejs/undici/commit/65eea9be3d147c8957e17ede3848c5ae409ca23e"><code>65eea9b</code></a> feat: add abort signal to body.dump() (<a href="https://redirect.github.com/nodejs/undici/issues/1993">#1993</a>)</li>
<li><a href="https://github.com/nodejs/undici/commit/0d2f4f1bf4b2d5e73b5b9a95c5aee83461606cca"><code>0d2f4f1</code></a> Add missing import (<a href="https://redirect.github.com/nodejs/undici/issues/1997">#1997</a>)</li>
<li><a href="https://github.com/nodejs/undici/commit/babed9cada1b5255d239b259825e32d4b0b85ae7"><code>babed9c</code></a> fix: remove unnecessary WeakRef (<a href="https://redirect.github.com/nodejs/undici/issues/2000">#2000</a>)</li>
<li><a href="https://github.com/nodejs/undici/commit/a0afde8ac32bfc47f88c0e268ff286a137861d7c"><code>a0afde8</code></a> fix: undici stream throwOnError (<a href="https://redirect.github.com/nodejs/undici/issues/1995">#1995</a>)</li>
<li><a href="https://github.com/nodejs/undici/commit/3606c3556aa637005c8123036bdebc9ffc4b77ec"><code>3606c35</code></a> wpt: update tests (<a href="https://redirect.github.com/nodejs/undici/issues/1984">#1984</a>)</li>
<li><a href="https://github.com/nodejs/undici/commit/71c3605a0e3321590cef51b2c177932fe66d2a1a"><code>71c3605</code></a> fix: correctly calculate resource timing duration (<a href="https://redirect.github.com/nodejs/undici/issues/1988">#1988</a>)</li>
<li>Additional commits viewable in <a href="https://github.com/nodejs/undici/compare/v5.14.0...v5.21.0">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=undici&package-manager=npm_and_yarn&previous-version=5.14.0&new-version=5.21.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)
- `@dependabot use these labels` will set the current labels as the default for future PRs for this repo and language
- `@dependabot use these reviewers` will set the current reviewers as the default for future PRs for this repo and language
- `@dependabot use these assignees` will set the current assignees as the default for future PRs for this repo and language
- `@dependabot use this milestone` will set the current milestone as the default for future PRs for this repo and language

You can disable automated security fix PRs for this repo from the [Security Alerts page](https://github.com/teletrace/teletrace/network/alerts).

</details>